### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Reiayana** [gcla/termshark#109]
## Prerequisites

Please verify these before submitting an issue.

- [ Yes ] I am running the latest versions of Termshark and Wireshark.
- [ Yes ] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [ Yes ] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

## Problem 
When doing a live capture, I found a bug, Error, can't do a live capture

### Screenshots as applicable 

![IMG_20210308_144229](https://user-images.githubusercontent.com/75322691/110290067-e4bd8f80-801c-11eb-818f-03f4a43f61cf.jpg)

Please also provide any relevant information about your environment

Android 9

**Comment by pocc** [comment]
It looks like tshark, which is a vital component of termshark, can't be found. This likely means that tshark either isn't installed or cannot be found on your PATH (tshark is sometimes packaged separately from wireshark).

What happens when you run `tshark -v`?
