### ISSUE TITLE
termshark wont start, stuck on "The termshark UI will start when packets are detected..." Even though packets are coming to the interface.

### ISSUE THREAD

**Issue by davehouser1** [gcla/termshark#110]
## Prerequisites

Please verify these before submitting an issue.

- [x] I am running the latest versions of Termshark and Wireshark.
- [x] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [x] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

## Problem 
When trying to run `termshark -i <interface>`
termshark wont start, stuck on "The termshark UI will start when packets are detected..." 

### Current Behavior
termshark wont start, stuck on "The termshark UI will start when packets are detected..."

### Expected Behavior
termshark should open when packets come to the interface.

## Context

Please provide the complete output of these commands:
- termshark v2.2.0

Please also provide any relevant information about your environment (OS, VM, pi,...)
- all commands run as root
- Ubuntu 18.04.
- I am using the .tar.gz binary download from the github tag. Used linux x64 version.
- golang version v1.10 (not sure if needed as termshark appears to be a compiled binary.
- I have tested with tcpdump and tshark, both show packets are appearing.

EDIT:
Tried rolling back everything, and using `snap install termshark`
this results in "Cannot capture on device <interface name>: exit status 1 (exit code 1)"

**Comment by pocc** [comment]
What happens when you run `tshark -i <interface>`? Do you see packets?

**Comment by davehouser1** [comment]
@pocc as my post says above, I see packets come though when running `tshark -i <interface>`

**Comment by davehouser1** [comment]
Update, was able to install fine via snap on a rhel 7.9 machine I have, using these instructions. And termshark actually works.
https://snapcraft.io/install/termshark/rhel

**Comment by gcla** [comment]
Hi @davehouser1 - out of interest, does termshark's log show anything useful on your Ubuntu 18.04 machine? `~/.cache/termshark/termshark.log`

If not, would you be willing to attach the output of the following command when running as root?

`strace -f -o termsharkstrace -s 256 -tt termshark -i <interface>`

If you're willing, do have a scan through first, I don't want to have it capture anything personal from your machine. If you are ok with it but would rather keep it private, feel free to email it to me - grclark@gmail.com

**Comment by davehouser1** [comment]
Sorry its been so long, I am coming back to this now. On a different VM I just deployed (OS: ubuntu 18.04). Thought I could load termshark again with snap,  same exact issue. I checked in ~/.cache, nothing in there for termshark. So I tried the other command.

Note: "ens160" is a valid network interface name on this system, confirmed with `ip -br addr show`

When running :
`strace -f -o termsharkstrace -s 256 -tt termshark -i ens160`
The terminal will freeze (I assume expected), I logged into a different session and tailed the termsharktrace, here is the output (only thing personal is paths and interface names, which is fine to share imo):

```
# tail -f termsharktrace
2055  14:32:38.786912 newfstatat(AT_FDCWD, "/snap/core/current/usr/bin/snap", {st_mode=S_IFREG|0755, st_size=18293136, ...}, 0) = 0
2055  14:32:38.786957 openat(AT_FDCWD, "/snap/core/current/usr/lib/snapd/info", O_RDONLY|O_CLOEXEC) = 5
2055  14:32:38.786999 epoll_ctl(4, EPOLL_CTL_ADD, 5, {EPOLLIN|EPOLLOUT|EPOLLRDHUP|EPOLLET, {u32=2162036384, u64=140142649937568}}) = -1 EPERM (Operation not permitted)
2055  14:32:38.787037 epoll_ctl(4, EPOLL_CTL_DEL, 5, 0xc4202817d4) = -1 EPERM (Operation not permitted)
2055  14:32:38.787075 fstat(5, {st_mode=S_IFREG|0644, st_size=13, ...}) = 0
2055  14:32:38.787130 read(5, "VERSION=2.50\n", 525) = 13
2055  14:32:38.787169 read(5, "", 512)  = 0
2055  14:32:38.787206 close(5)          = 0
2055  14:32:38.787257 execve("/snap/core/current/usr/bin/snap", ["termshark", "-i", "ens160"], 0xc420301400 /* 19 vars */ <unfinished ...>
2056  14:32:38.787295 <... pselect6 resumed> ) = 0 (Timeout)
```

Let me know if you want to check / try anything else?

**Comment by davehouser1** [comment]
Any update on this? I am faced with having to install Termshark on ubuntu 18.04 again. Same issue keeps happening. Termshark will refuses to change from the "(The Termshark UI will start when packets are detected)". Am forced to `kill -9` the process every time. This does not happen on centos / RHEL systems. However I am able to open .pcap files with termshark with no problems in ubuntu 18.04. One more note: If i use the apt repo to install (v1.0.0), termshark will start but NO packets will appear on the gui. Which leads me to believe that termshark is just not seeing the packets.

**Comment by gcla** [comment]
Hi @davehouser1 - I'll dig in again this evening after work - more soon!

**Comment by gcla** [comment]
Hi @davehouser1 - please could you try the following from a root shell:

```bash
snap connect termshark:network-control
snap connect termshark:bluetooth-control
snap connect termshark:firewall-control
snap connect termshark:ppp
snap connect termshark:raw-usb
snap connect termshark:removable-media
```
I hope that allows the snap version of termshark to successfully capture packets (I tried a before and after with an Ubuntu 18.04 VM) Let me know! As for the failing ctrl-c, that'll require a code change from me, so I've made a note.

**Comment by davehouser1** [comment]
@gcla Sir, you have done it again. That worked!
I didn't know I needed to integrate snap to devices on the system. 
Note that when packets start to collect, I can select "q" to quit and termshark exits properly. So workaround to exit is to just make sure packets come to the interface. 
Thank you again!
