### ISSUE TITLE
termshark 2.2.x not visible 😱

### ISSUE THREAD

**Issue by zoulja** [gcla/termshark#114]
## Prerequisites

Please verify these before submitting an issue.

- [x] I am running the latest versions of Termshark and Wireshark.
- [x] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [x] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

## Problem 
termshark 2.2.x window is not visible
termshark 2.0.3 is ok
### Current Behavior
After startup termshark window is not visible
termshark is clearly running, I can exit by pressing Q + Enter
### Expected Behavior
termshark window must be visible

Please describe the behavior you are expecting. 

### Screenshots as applicable 
![termshark](https://user-images.githubusercontent.com/10187203/111449197-37373400-8720-11eb-942c-861e63b9297a.gif)

### Steps to Reproduce
1.Connect from Windows to Linux(tested on Ubuntu 20.04 and Centos 7.5) using Putty or any ssh client
2. Start termshark for example termshark -r test.pcap
3. Some loading percents(in right top corner) are visible in the beginning for 2 seconds, after that only black screen is seen.

## Context

Good one:
# termshark -v
termshark v2.0.3
# termshark -v | cat
TShark 1.10.14 (Git Rev Unknown from unknown)

Copyright 1998-2015 Gerald Combs <gerald@wireshark.org> and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with GLib 2.56.1, with libpcap, with libz 1.2.7, with POSIX
capabilities (Linux), without libnl, with SMI 0.4.8, with c-ares 1.10.0, with
Lua 5.1, without Python, with GnuTLS 3.3.29, with Gcrypt 1.5.3, with MIT
Kerberos, without GeoIP.

Running on Linux 3.10.0-862.9.1.el7.x86_64, with locale en_US.UTF-8, with
libpcap version 1.5.3, with libz 1.2.7.
Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)

Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-44).

Bad one:
# termshark -v
termshark v2.2.0
# termshark -v | cat
TShark 1.10.14 (Git Rev Unknown from unknown)

Copyright 1998-2015 Gerald Combs <gerald@wireshark.org> and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with GLib 2.56.1, with libpcap, with libz 1.2.7, with POSIX
capabilities (Linux), without libnl, with SMI 0.4.8, with c-ares 1.10.0, with
Lua 5.1, without Python, with GnuTLS 3.3.29, with Gcrypt 1.5.3, with MIT
Kerberos, without GeoIP.

Running on Linux 3.10.0-862.9.1.el7.x86_64, with locale en_US.UTF-8, with
libpcap version 1.5.3, with libz 1.2.7.
Intel Xeon E3-12xx v2 (Ivy Bridge, IBRS)

Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-44).

Strace logs attached:

[strace_bad.log](https://github.com/gcla/termshark/files/6155367/strace_bad.log)
[strace_good.log](https://github.com/gcla/termshark/files/6155370/strace_good.log)

**Comment by gcla** [comment]
Yikes, sorry @zoulja ! Please could you confirm the bug is still there in this build?

Linux: https://storage.googleapis.com/termshark/3af66fdad5cf31c2443ec4848371526574082007/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/3af66fdad5cf31c2443ec4848371526574082007/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/3af66fdad5cf31c2443ec4848371526574082007/termshark_windows_amd64/termshark.exe

**Comment by zoulja** [comment]
Hi @gcla 
Unfortunately the issue still persits

**Comment by gcla** [comment]
Hi @zoulja - after you've launched putty, but before you start termshark, could you try:
```
echo original is $TERM
export TERM=xterm-256color
```
If that makes termshark visible again, could you tell me what the original TERM is? I suspect xterm. If this env var gets things working then I'd be interested to know what you see when you launch termshark v2.0.3 in putty without this env var change. Do you see a black and white termshark, or maybe an 8-color termshark?

Thanks!

**Comment by zoulja** [comment]
Yes, it solves the issue, thanks a lot!
Original one was **xterm** (and also **screen** in another setup I tried)
v2.0.3 actually looks the same 🙄

**Comment by oskar456** [comment]
I think this issue is not resolved. I had the same issue with `TERM=screen`, I was able to work it around by switching to `TERM=screen-256color`. But I think there should be some visible output even with the former setting.

**Comment by gcla** [comment]
Hi @oskar456 - ok, I'll reopen and think about a solution. Maybe a 2-color mode wouldn't be too much work.

**Comment by RduMarais** [comment]
Hi all,

I am running termshark inside Microsoft's WSL2 on a Kali Linux machine, and I have the same issue, and can not see the interface, whether it is with `xterm-256color` or `screen-256color`. 
Changing the termshark theme does help either.
There might be some specific issues in the display of WSL2 but I guess it is still related to the issue above.
Thx for your work !

**Comment by gcla** [comment]
Thanks @RduMarais , I'll try to reproduce in a similar setup

**Comment by fabrijustiniano19** [comment]
Any news on this? I'm having the same problem on v2.2

**Comment by gcla** [comment]
Sorry @maplehobo , not yet, but I will make this a priority.

**Comment by gcla** [comment]
Hi @maplehobo - can you describe the environment in which you're running termshark? I'll reproduce from there. Of particular interest to me are OS, terminal emulator software and the values of TERM and COLORTERM in the shell.

**Comment by fabrijustiniano19** [comment]
Sure;
OS: Pop!_OS 21.04
Terminal: gnome-terminal
TERM: xterm-256color
COLORTERM: truecolor

**Comment by gcla** [comment]
Hi @maplehobo - I see the same problem with termshark installed via `apt-get install` on PopOS. It seems to be something related to the way the package is built from source. I'm digging into the Debian/Ubuntu packaging code to try to understand what's different, but in the meantime, could you try the following from a shell:

```
git clone https://github.com/gcla/termshark
cd termshark
go install ./...
```

The binary will be available as `~/go/bin/termshark`. Could you try running that to see if the colors show up?

**Comment by gcla** [comment]
Hi @RduMarais - I tried termshark today on Kali under WSL2 - seems like the same issue as @maplehobo is seeing. As best as I can tell, the Kali package is based on the Debian termshark package. Maybe it's identical. If you build from source as described in https://github.com/gcla/termshark/issues/114#issuecomment-903210439, I suspect termshark will work better. It's not a fix for the package though - working on that.

**Comment by gcla** [comment]
Hi @maplehobo and @RduMarais - I found the issue in the Debian packaging rules for termshark. I've submitted a bug report using Debian's official mechanism: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992831

I'm not sure what the turnaround time is, so in the meantime, if you don't want to compile from source, a workaround is to copy termshark's default theme into your config directory. Download this to /tmp:

https://raw.githubusercontent.com/gcla/termshark/master/assets/themes/default-256.toml

Then type something like:

```bash
$ cd ~/.config/termshark
$ mkdir themes
$ cp /tmp/default-256.toml ./themes/
```

Then set `TERM=xterm-256color` and run termshark. From the termshark command-line (via the `:` key) you can type

```
set term xterm-256color
```

to make the terminal setting permanent for that user (saved in `~/.config/termshark/termshark.toml`)

Let me know if it helps!

**Comment by fabrijustiniano19** [comment]
Yes, this worked!, thank you so much.

> Hi @maplehobo - I see the same problem with termshark installed via `apt-get install` on PopOS. It seems to be something related to the way the package is built from source. I'm digging into the Debian/Ubuntu packaging code to try to understand what's different, but in the meantime, could you try the following from a shell:
> 
> ```
> git clone https://github.com/gcla/termshark
> cd termshark
> go install ./...
> ```
> 
> The binary will be available as `~/go/bin/termshark`. Could you try running that to see if the colors show up?

I tried doing this on a VM and it froze the VM when launching the binary. Although might have just been my impatience as I was in a hurry. :P

**Comment by ssgelm** [comment]
This package is now fixed in Debian unstable (in version 2.2.0-2). It will make it to testing (bookworm) in ~2 days. I submitted a request to pull the fix into bullseye at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=992836. If there are issues getting it approved I will upload it to `bullseye-backports`, but I don't expect it to be a problem. Sorry to have created this issue in the first place!

**Comment by gcla** [comment]
It's ok @ssgelm , thanks for the quick turnaround and thanks for all the packaging work! :heart:

**Comment by gcla** [comment]
Hi @oskar456 and @zoulja - I just pushed a commit that adds an 8-color default theme to termshark. It's built-in to the binary, like the others, so all you need to try it is a new termshark binary. It'll be in effect if you use an 8-color TERM setting like xterm or screen. I think I've broken my Travis builds, but if you can build from source, that'll do the job. If you have the Go compiler, this should work:

```
git clone https://github.com/gcla/termshark
cd termshark
go install ./...
```
Then the binary will be in `~/go/bin/`.

**Comment by gcla** [comment]
Hi again @zoulja and @oskar456 - here are pre-built binaries, if you'd prefer:

Linux: https://storage.googleapis.com/termshark/564d612555a3d6c4f5f9eba8b18ce704c38607dd/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/564d612555a3d6c4f5f9eba8b18ce704c38607dd/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/564d612555a3d6c4f5f9eba8b18ce704c38607dd/termshark_windows_amd64/termshark.exe

**Comment by gcla** [comment]
To try to make this less troublesome in the future, I just pushed a commit that nudges the user towards a 256-color mode if that's available: https://github.com/gcla/termshark/commit/1c15fed1131299a232bb229cd223faaff923bb73

If you'd like to try it out, here are links to the latest - not available for Windows though:

Linux: https://storage.googleapis.com/termshark/1c15fed1131299a232bb229cd223faaff923bb73/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/1c15fed1131299a232bb229cd223faaff923bb73/termshark_darwin_amd64/termshark

![image](https://user-images.githubusercontent.com/45680/131779036-ed5edfc0-afd6-457d-b7b3-cd0b4ea8636d.png)

**Comment by gcla** [comment]
I think this issue is now resolved, via the 8-color theme and the Debian packaging fix. Please re-open if it returns.
