### ISSUE TITLE
--version is incorrect when installing with go get

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#12]
When using `go get github.com/gcla/termshark/cmd/termshark`, the version is `v<localbuild>`. Confirmed on Macos 10.14.

**Comment by pocc** [comment]
Getting the same thing for `termshark --help`:

```bash
bash-5.0$ termshark --help
termshark v<localbuild>

A wireshark-inspired terminal user interface for tshark. Analyze network traffic interactively from your terminal.
See https://github.com/gcla/termshark for more information.

Usage:
  termshark [FilterOrFile]


// output truncated ...
```

**Comment by gcla** [comment]
Thanks, you are right - I should make this better. I used goreleaser to make the binaries on github - it runs something like:

go install -ldflags="-X github.com/gcla/termshark.Version=1.0.0" ./... 

It would be better if absent that flag, the last release version was used, maybe with an asterisk next to it.

**Comment by k0ste** [comment]
@gcla `go build` will be supported?

**Comment by gcla** [comment]
Hi @k0ste - yes, go build ought to be supported. This will fix the problem:

go build -ldflags="-X github.com/gcla/termshark.Version=1.0.0" github.com/gcla/termshark/cmd/termshark

but it's ugly. Maybe I should put the version number in the code for now so that regular builds don't display the ugly "localbuild", and until I decide on a better approach.

**Comment by gcla** [comment]
I changed the hard-coded version to "1.0.0++" for now, intended to mean 1.0.0 + some extra commits. We'll have to remember to update this when a new release is tagged, until I find a better way. I'd love to keep it simple and have go build/go install just work, and not need go generate.

**Comment by k0ste** [comment]
@gcla for package maintainers we definitely need `go build` support.

* Download tar.gz release from github releases;
* Satisfy dependencies;
* `go build`, i.e. without git;

**Comment by QuLogic** [comment]
Is there a reason it's `Version` and not `version`, which is automatically set by Goreleaser? https://goreleaser.com/environment/#using-the-main-version

**Comment by pocc** [comment]
In golang, variables with capitals are exported and accessible to external packages. It doesn't look like this is strictly necessary though as the [example's default]( https://goreleaser.com/customization/#Name%20Templates) is lowercase: 

```bash
ldflags:
     - -s -w -X main.version={{.Version}}
```

**Comment by gcla** [comment]
Hi @QuLogic - no good reason at all, I didn't know goreleaser did that automatically
