### ISSUE TITLE
Does not build on riscv64

### ISSUE THREAD

**Issue by nmeum** [gcla/termshark#127]
Hi, I just wanted to let you know that termshark does not build on riscv64 by default. This is due to following issues:

1. [github.com/kr/pty](https://github.com/kr/pty) does not support riscv64. However, the repository is a fork and archived. The original version [github.com/creack/pty](https://github.com/creack/pty) does support riscv64. Maybe switch to that?
2. [Similar to arm64](https://github.com/gcla/termshark/commit/5132d71726b7199b3e856a8cd0dafa585196d00b), the `dup2` syscall is not available on riscv64. You can just use `dup3` as set the last argument (the flags argument) to zero. This is equivalent to `dup2`. There should be no need for a custom `DumpcapExt` implementation for arm64/riscv64 IMHO.

**Comment by gcla** [comment]
Thanks for the report @nmeum , I'll look into this.

**Comment by qbit** [comment]
fwiw, the creack/pty also will allow termshark to build on OpenBSD/armv7,arm64 (and mips64 once https://github.com/creack/pty/pull/123 lands).

**Comment by gcla** [comment]
Thanks @nmeum and @qbit - please let me know if the master branch needs more work for your needs.

**Comment by gcla** [comment]
I'll close this for now because I think it's resolved on master - but please re-open if it's not resolved.
