### ISSUE TITLE
Find in packets list

### ISSUE THREAD

**Issue by elig0n** [gcla/termshark#131]
Ability to search the packet list columns for text strings like in wireshark

**Comment by gcla** [comment]
Thanks for the suggestion @elig0n , I'll look into it.

**Comment by gcla** [comment]
Hi @elig0n - if you have the time, would you mind trying out this new feature? Here's how to build it:

```
git clone https://github.com/gcla/termshark
cd termshark
git checkout search
go install ./...
```

Then you should have a termshark binary in `~/go/bin/`. I'll update the various documents soon, but here's what you need to know:

- hit ctrl-f to open the search bar. Ctrl-f will focus on the search input, if it doesn't have focus, else close the search bar.

- use the dropdown menus to select
  - the data searched:
    - PSML data (the list view)
    - PDML data (the struct view)
    - raw packet data (the hex view)
  - the type of search term
    - string (+ case)
    - regex (+ case)
    - hex
    - display filter - this is a special case and searches by matching packets against the filter

- hit the Find button or hit enter in the search input to run the search

- if you want to cancel the search mid-way, hit ctrl-c or click the Stop button on the progress spinner.

Here's a screenshot:

![image](https://user-images.githubusercontent.com/45680/171069229-98e5c2b7-39f7-48af-b737-6521bc7b390e.png)

**Comment by gcla** [comment]
Hi @elig0n - I realized I messed up the go.mod file and it probably isn't compiling for anyone except me! I pushed some fixes and merged everything back to master. If you want, here are some copies of the latest binaries from this branch:

Linux: https://storage.googleapis.com/termshark/b92b83cdffe08e2164ff75b74e6828217afc8806/termshark_linux_amd64_v1/termshark

macOS: https://storage.googleapis.com/termshark/b92b83cdffe08e2164ff75b74e6828217afc8806/termshark_darwin_amd64_v1/termshark

Windows: https://storage.googleapis.com/termshark/b92b83cdffe08e2164ff75b74e6828217afc8806/termshark_windows_amd64_v1/termshark.exe

Or if you want to build it yourself, this should work now with recent versions of Go:

```bash
go install github.com/gcla/termshark/v2/cmd/termshark@master
```

**Comment by gcla** [comment]
With v2.4 out, I'll close this. Feedback on search most welcome!
