### ISSUE TITLE
Termshark

### ISSUE THREAD

**Issue by Commaders** [gcla/termshark#134]
## Prerequisites

Please verify these before submitting an issue.

- [x] I am running the latest versions of Termshark and Wireshark.
- [x] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [x] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

### Current Behavior

Please describe the behavior you are seeing. 

### Expected Behavior

Please describe the behavior you are expecting. 

### Screenshots as applicable 

* Provide screenshots of wireshark/tshark if that's what the expectation is based on.
* Provide screenshots of the problem state.

## Context

Please provide the complete output of these commands:

* termshark -v (or termshark -vv if running from git/HEAD)
* termshark -v | cat

Please also provide any relevant information about your environment (OS, VM, pi,...)

**Comment by Commaders** [comment]
## termshark

**Comment by pocc** [comment]
Hello! Is there an issue or question you have? It looks like you've just posted the default bug report.

**Comment by gcla** [comment]
Closing
