### ISSUE TITLE
Feature Request: Dark Theme

### ISSUE THREAD

**Issue by lennartkoopmann** [gcla/termshark#17]
First of all, thank you so much for this great project.

My first feature request would be a dark theme. The fairly bright colors can be a little overwhelming in dark environments.

**Comment by gcla** [comment]
Great idea, I'll do it :-)

**Comment by gcla** [comment]
Hi - I've pushed a new branch called "darkmode". Would you be willing to give it a try? You should be able to compile it up like this:

```bash
git clone https://github.com/gcla/termshark
cd termshark
git checkout origin/darkmode
export GO111MODULE=on
go install -ldflags="-X github.com/gcla/termshark.Version=1.0.0+" ./...
```

Then termshark will be in `~/go/bin/`.

You can run it like this:

```bash
termshark ... --dark-mode
```

Or set it permanently in the "main" section of `XDG_CONFIG_HOME/termshark.toml`:

```toml
[main]
  dark-mode = true
```

You can also toggle it in the running application itself via the menu button.

I hope it looks okay when the terminal supports >= 256 colors (e.g. `TERM=xterm-256color`) or just 8 colors (e.g. `TERM=xterm`). Let me know how it looks, what UI elements you'd like altered, etc :-)

**Comment by kutsan** [comment]
I think dark theme should be default IMO.

**Comment by pocc** [comment]
Verified working, Macos 10.14 via both command flag and menu item. 

<img width="1146" alt="Screen Shot 2019-06-07 at 1 11 02 PM" src="https://user-images.githubusercontent.com/10995145/59103117-e0cf7b80-8925-11e9-885c-b949fbb2d58c.png">

**Comment by gcla** [comment]
Hi @kutsan - I merged this back to master, and made the in-app toggle (via menu->d) persist the setting to the config file. So making dark-mode the persistent default can be done quickly without editing a config file.
