### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by ghost** [gcla/termshark#19]
Hi,

When I launch termshark -i wlan0, I get this error

`goroutine 1 [running]:
main.makePacketListModel(0xc0002881e0, 0x4, 0xa, 0xc001a70000, 0x2e, 0x40, 0xb459c0, 0xc0001224d0, 0xc002cbac20)
	/usr/gocode/src/github.com/gcla/termshark/cmd/termshark/termshark.go:1529 +0x721
main.updatePacketListWithData(0xc0002881e0, 0x4, 0xa, 0xc001a70000, 0x2e, 0x40, 0xb459c0, 0xc0001224d0)
	/usr/gocode/src/github.com/gcla/termshark/cmd/termshark/termshark.go:1536 +0x7e
main.updatePacketViews.BeforeBegin.func1.1.1.1(0xb459c0, 0xc0001224d0)
	/usr/gocode/src/github.com/gcla/termshark/cmd/termshark/termshark.go:1048 +0xd0
github.com/gcla/gowid.RunFunction.RunThenRenderEvent(0xab8b30, 0xb459c0, 0xc0001224d0)
	/usr/gocode/src/github.com/gcla/gowid/app.go:720 +0x3a
github.com/gcla/gowid.(*App).RunThenRenderEvent(0xc0001224d0, 0xb39220, 0xab8b30)
	/usr/gocode/src/github.com/gcla/gowid/app.go:600 +0x47
main.cmain(0x0)
	/usr/gocode/src/github.com/gcla/termshark/cmd/termshark/termshark.go:3114 +0x61c7
main.main()
	/usr/gocode/src/github.com/gcla/termshark/cmd/termshark/termshark.go:2109 +0x4b`

I also get the same error when I try to read a pcap file 'termshark -r test.pcap'

I'm using the Golang-go 1.11.6 btw

**Comment by pocc** [comment]
Thanks for reporting this. Please post `tshark -v`

**Comment by ghost** [comment]
I think I found where my issue is.

it's related to Wireshark and Tshark version, you require v3.0

I only have v2.6.8 on my kali system

**Comment by pocc** [comment]
Cheers. Closing this - let us know if it's not tshark version.

**Comment by gcla** [comment]
I think v2.6.8 is fine, that's the version I'm running. I only found problems with versions < 1.10.2 from a few years back. I'll re-open this to investigate. Just to confirm, @jJit0 , that the problem still exists for you? Can you let us know if you're able to get data back from a command like this:

```bash
tshark -i wlan0 -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i"
```

Thanks!

**Comment by ghost** [comment]
Hello gcla,

Here is output of your command

`tshark -i wlan0 -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i"
Running as user "root" and group "root". This could be dangerous.
<?xml version="1.0" encoding="utf-8"?>
<psml version="0" creator="wireshark/2.6.8">
<structure>
<section>Source</section>
<section>Destination</section>
<section>Protocol</section>
<section>Info</section>
</structure>

Capturing on 'wlan0'
<packet>
<section>10.199.0.126</section>
<section>255.255.255.255</section>
<section>DB-LSP-DISC</section>
<section>Dropbox LAN sync Discovery Protocol</section>
</packet>

<packet>
<section>10.199.2.22</section>
<section>10.199.7.255</section>
<section>UDP</section>
<section>54915 \xe2\x86\x92 54915 Len=263</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.2.22</section>
<section>10.199.7.255</section>
<section>UDP</section>
<section>54915 \xe2\x86\x92 54915 Len=263</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB ELJTFSXNDF&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB DZZZDMOJS&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

^C<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB ELJTFSXNDF&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB DZZZDMOJS&lt;00&gt;</section>
</packet>

14 packets captured
</psml>
`

I also installed termshark from Debian unstable, but I still have the same error.
my wireshark version is 2.6.8-1.1

**Comment by jJit0** [comment]
Hello gcla,

Here is output of your command

`tshark -i wlan0 -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i"
Running as user "root" and group "root". This could be dangerous.
<?xml version="1.0" encoding="utf-8"?>
<psml version="0" creator="wireshark/2.6.8">
<structure>
<section>Source</section>
<section>Destination</section>
<section>Protocol</section>
<section>Info</section>
</structure>

Capturing on 'wlan0'
<packet>
<section>10.199.0.126</section>
<section>255.255.255.255</section>
<section>DB-LSP-DISC</section>
<section>Dropbox LAN sync Discovery Protocol</section>
</packet>

<packet>
<section>10.199.2.22</section>
<section>10.199.7.255</section>
<section>UDP</section>
<section>54915 \xe2\x86\x92 54915 Len=263</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.109</section>
<section>10.199.7.255</section>
<section>BROWSER</section>
<section>Become Backup Browser</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.2.22</section>
<section>10.199.7.255</section>
<section>UDP</section>
<section>54915 \xe2\x86\x92 54915 Len=263</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB ELJTFSXNDF&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB DZZZDMOJS&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB IMQBRDTXRHRTAZM&lt;00&gt;</section>
</packet>

^C<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB ELJTFSXNDF&lt;00&gt;</section>
</packet>

<packet>
<section>10.199.0.212</section>
<section>10.199.7.255</section>
<section>NBNS</section>
<section>Name query NB DZZZDMOJS&lt;00&gt;</section>
</packet>

14 packets captured
</psml>
`

I also installed termshark from Debian unstable, but I still have the same error.
my wireshark version is 2.6.8-1.1

**Comment by gcla** [comment]
Hi @jJit0 - thanks for the output, and most strange - here's the sort of thing I see

```
gcla@elgin:~$ tshark -i wlan1 -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i"
<?xml version="1.0" encoding="utf-8"?>
<psml version="0" creator="wireshark/2.6.8">
<structure>           
<section>No.</section>                                                              
<section>Time</section>
<section>Source</section>
<section>Destination</section>
<section>Protocol</section>
<section>Length</section>     
<section>Info</section>          
</structure>                    
                      
Capturing on 'wlan1'  
<packet>                                                                                                                                          
<section>1</section>
<section>0.000000000</section>
<section>192.168.86.246</section>
<section>52.21.251.252</section>
<section>TLSv1.2</section>    
<section>129</section>          
<section>Application Data</section>
</packet>             
...
```

i.e. XML output. Is it possible you have an old tshark in your PATH that is overriding the one from the wireshark package you're installing? But that doesn't quite add up because termshark, by default, picks the tshark that would come first in PATH and checks to make sure the version is compatible. So it would seem whatever tshark is being run on your machine is validated by termshark... Maybe the tshark you're installing somehow doesn't have XML support compiled in? Clutching at straws here :)

A couple of things:

- could you run `tshark -v` and paste the output?
- in `~/.config/termshark/termshark.toml` you can set a specific tshark to use e.g.

```toml
[main]
  tshark = "/opt/wireshark-2.6.8/bin/tshark"
```

Maybe point it to the tshark that is part of the wireshark package, and see if that helps?

**Comment by ghost** [comment]
Hi gcla,

No need for all that, you just gave me the clue to look into /root/.config/wireshark.
Brilliant idea ;-)
The problem was in wireshark different columns, in fact.

I use to disable N°, Time and Length columns, to have more readability on packets, and by enabling them, termshark worked again.

Give it a try, and tell me if it's reproducible for you too.

It can be problematic, if you want to disable some columns in wireshark. I hope there will be a fix in next major release

**Comment by gcla** [comment]
Aha - yes, you're right, the column choices are currently fixed in termshark, unfortunately. :-/ I'll close this issue and open a feature request for configurable columns.
