### ISSUE TITLE
Publish on aur.archlinux.org

### ISSUE THREAD

**Issue by jerry73204** [gcla/termshark#2]
I make it available on [AUR](https://aur.archlinux.org/packages/termshark-bin) for Arch Linux users. This is a binary package, which simply copies the released binary to install directory. Enjoy it. The issue page is left for discussion.

**Comment by gcla** [comment]
Thank you!

**Comment by Thann** [comment]
I made `termshark-git` that compiles from source, ping me if there are any issues with it  ^>^
