### ISSUE TITLE
Quit is not working

### ISSUE THREAD

**Issue by mingrammer** [gcla/termshark#27]
<img width="353" alt="Screen Shot 2019-04-25 at 4 39 19 PM" src="https://user-images.githubusercontent.com/6178510/56717907-b14f2000-6778-11e9-99e7-f9015baa10fb.png">

In the above box, I tried both `enter` and `space` keys, but the termshark was not closed. `cancel` button works well.

I'm using macOS 10.14 and latest termshark.

**Comment by gcla** [comment]
Thanks, that's concerning. Does this happen all the time, even when you just open up termshark then try to close it without interacting with the pcap? That is - the Ok button never works, or sometimes gets in this state? Thanks.

**Comment by mingrammer** [comment]
Yes, it happens all the time. I opened the box while filtering the packets.

**Comment by gcla** [comment]
Hi - please could you try with any build from 07e6db754bfc0fa7f2174021fe159b7a802cbd5c onwards? I think I found the cause of this issue.

**Comment by mingrammer** [comment]
It works now. Thank you!
