### ISSUE TITLE
Packaging for NixOS

### ISSUE THREAD

**Issue by winpat** [gcla/termshark#33]
I'm currently in the process of packaging termshark for [Nix](https://nixos.org/nix/)/[NixOS](https://nixos.org/). I would like to build the tagged versions from source. Could you give me a hint on how to compile termshark?

I've tried the following without success:
```
➜ ~/vcs/termshark (v1.0.0) go version
go version go1.11.6 linux/amd64
➜ ~/vcs/termshark (v1.0.0) export GO111MODULE=on
➜ ~/vcs/termshark (v1.0.0) go build  -o termshark *.go
# command-line-arguments
./copycommand_darwin.go:7:5: CopyToClipboard redeclared in this block
	previous declaration at ./copycommand_android.go:7:5
./copycommand.go:9:5: CopyToClipboard redeclared in this block
	previous declaration at ./copycommand_darwin.go:7:5
./copycommand_windows.go:7:5: CopyToClipboard redeclared in this block
	previous declaration at ./copycommand.go:9:5
./have_fdinfo_linux.go:7:7: HaveFdinfo redeclared in this block
	previous declaration at ./have_fdinfo.go:9:20
```

Thanks :smile:

**Comment by winpat** [comment]
The packaging work happens here https://github.com/NixOS/nixpkgs/pull/60417

**Comment by winpat** [comment]
I've found a way to compile the termshark module.

**Comment by gcla** [comment]
Hi @winpat - if you can give me a quick guide to installing termshark on NixOS, I'll add it to the platforms doc :-)

**Comment by winpat** [comment]
@gcla Cool! There you go.
```
nix-env -iA nixpkgs.termshark
```
