### ISSUE TITLE
Published on the Snap Store

### ISSUE THREAD

**Issue by mharjac** [gcla/termshark#34]
I've published termshark on the Snap store so it can be easily installed on almost all major distros just by issuing: `snap install termshark`  
After installation, it requires some additional permissions:
```
snap connect termshark:network-control
snap connect termshark:bluetooth-control
snap connect termshark:firewall-control
snap connect termshark:ppp
snap connect termshark:raw-usb
snap connect termshark:removable-media
```

**Comment by pocc** [comment]
Cheers @mharjac! Thanks for your work on this.

**Comment by gcla** [comment]
I'm new to snap and just tried it out - thanks @mharjac :-)

Just to be sure - I think it's the case that snap doesn't yet support filesystem capabilities, is that your understanding too? i.e. I was able to run the snap termshark like this

```bash
$ sudo termshark -i eth0
```
but not as an unprivileged user. Turned up this link by googling: https://forum.snapcraft.io/t/wireshark-and-setcap/9629

I'm on Ubuntu 18.10 at the moment.

One other very minor thing, and this is my fault - when it runs, it displays `v<localbuild>` at the top. I should've built the version in from the beginning :-/ If it's an easy thing to rebuild, you can get the current version in by compiling like this

```bash
$ go install -ldflags="-X github.com/gcla/termshark.Version=1.0.0" ./... 
```

But not a big deal! Thanks for the work.

**Comment by gcla** [comment]
oh, I'll update the README, can I add your name to it?

**Comment by mharjac** [comment]
> Just to be sure - I think it's the case that snap doesn't yet support filesystem capabilities, is that your understanding too? 

Yes, you're right. Currently it isn't possible to execute it without root privileges.

> One other very minor thing, and this is my fault - when it runs, it displays `v<localbuild>` at the top. I should've built the version in from the beginning :-/ If it's an easy thing to rebuild, you can get the current version in by compiling like this

Don't worry about that, it's just minor visual defect :) I've removed source-tag option from snapcraft.yaml, so from now on your every commit should trigger automatic rebuild and publish it to the edge channel and I would manually promote every stable release to the stable channel.

**Comment by mharjac** [comment]
> oh, I'll update the README, can I add your name to it?

Yeah, you have my permission :)

**Comment by tkisason** [comment]
awesome! :+1:

**Comment by gcla** [comment]
Hi @mharjac - would it be possible for you to update the snap package to v2.0.2? Many thanks!

**Comment by mharjac** [comment]
> Hi @mharjac - would it be possible for you to update the snap package to v2.0.2? Many thanks!

Hey! I've tried to build new snap but it failed with the following errors while building app:
```
github.com/gcla/tail/tail.go:188:45: cannot use &tail.Tomb (type *"github.com/gcla/tail/vendor/gopkg.in/tomb.v1".Tomb) as type *"github.com/hpcloud/tail/vendor/gopkg.in/tomb.v1".Tomb in argument to tail.watcher.BlockUntilExists

github.com/gcla/tail/tail.go:327:49: cannot use &tail.Tomb (type *"github.com/gcla/tail/vendor/gopkg.in/tomb.v1".Tomb) as type *"github.com/hpcloud/tail/vendor/gopkg.in/tomb.v1".Tomb in argument to tail.watcher.ChangeEvents
```

**Comment by gcla** [comment]
I think I've messed up the tags... Could you try the following:

```bash
export GO111MODULE=on
go install github.com/gcla/termshark/v2/cmd/termshark
```

Then try `~/go/bin/termshark -v` ?

Thanks :)

**Comment by gcla** [comment]
Sorry to pester you @mharjac - any luck with the snap? A couple of redditors were trying to install that way.

**Comment by mharjac** [comment]
Unfortunately, not. As it seems, snapcraft's go plugin [doesn't support go modules](https://forum.snapcraft.io/t/go-modules/7265) so I'm trying to override that.

**Comment by mharjac** [comment]
Finally... 2.0.2 released in stable channel.

**Comment by gcla** [comment]
Many thanks @mharjac!
