### ISSUE TITLE
deb package

### ISSUE THREAD

**Issue by NicolaiSoeborg** [gcla/termshark#38]
I would like a `.deb` package for this tool.

Packaging a single binary as a `.deb` package is fairly simple [0], but will ofc require a bit of extra time when releasing.  Could you be convinced to do it?  Or can I create an "official" PPA for the tool?

[0] Shameless plug:  I made the tool [ELF*2*deb](https://github.com/NicolaiSoeborg/ELF2deb) to automate the "anything-to-deb" process.

**Comment by pocc** [comment]
Feel free to do all of the above. If you create a PPA, please make a PR for the README.md. We'll want to document this addition under the `Install Packages` section in the README.md, where you can tag yourself as maintainer.

I took a look at your project and added a bunch of issues :)
