### ISSUE TITLE
UI visualization problem (lots of ????) on Raspberry 3B+ aarch64 build

### ISSUE THREAD

**Issue by gdluca** [gcla/termshark#48]
Hi,

I compiled Termshark on my Raspberry 3B+ running Arch Linux ARM aarch64 and go1.12.7 linux/arm64.

When I run it, the UI looks like this:

https://imgur.com/6I4D6PG

What am i missing? 

Thanks!

**Comment by pocc** [comment]
This looks like a problem with unicode on your system as some of the [Box-drawing characters](https://en.wikipedia.org/wiki/Box-drawing_character) are not rendering correctly. Are you using PuTTY/ssh to access the RPi or connected directly with keyboard/mouse/monitor? It looks like differing encodings between PuTTY and the target terminal can [cause issues](https://www.raspberrypi.org/forums/viewtopic.php?t=21606).

Please also respond with the output of these commands:

```bash
echo $LC_CTYPE
echo $LANG
```

**Comment by gdluca** [comment]
Thank you pocc.
I didn't set an env for LC_CTYPE.
Set it to  LC_CTYPE=en_US.UTF-8 fixed my problem.

And yes, I was using PuTTY.
