### ISSUE TITLE
tshark finds no capture device

### ISSUE THREAD

**Issue by sagis-tikal** [gcla/termshark#5]
When termshark is executed with root permissions it cannot find any device. ends up printing the following error: "Giving up waiting for  :  <nil>"

Tried to use both the pre-compiled version and to compile it using the with GO111MODULE=on
termshark version: 1.0.0
tshark version: TShark (Wireshark) 3.0.1 (Git)
OS version: 4.19.35-1-MANJARO (inside of a VirtualBox VM)

![image](https://user-images.githubusercontent.com/46102019/56562826-ffb2c200-65b2-11e9-942c-38ed2513f137.png)

Thanks for this good-looking app :)

**Comment by sagis-tikal** [comment]
P.S. tshark works perfectly - so it doesn't seem to be a problem within it.

**Comment by sagis-tikal** [comment]
Seems to work with root permissions **and** interface flag

**Comment by hook-s3c** [comment]
also having an issue here
