### ISSUE TITLE
Never get HEX data

### ISSUE THREAD

**Issue by inzel** [gcla/termshark#50]
I am on a mac and installed termshark via brew. For some reason I am not able to see hex data... ever. I have tried multiple terminals as well as live data and reading from a pcap.

Has anyone experienced this?

**Comment by pocc** [comment]
If you have a question about things that you see, it would be helpful if you could add a screenshot of the problem. If your expectation of how the hex data should work is based on xxd/Wireshark/tshark/etc., it would be helpful if you could include a screenshot of the "expected" behavior as well.

Cheers

**Comment by pocc** [comment]
Hey just want to make sure that this isn't something simple. Have you tried to press `\`, "Toggle Pane Zoom"? It's possible that the layers/hex view aren't present because they're hidden.

**Comment by inzel** [comment]
Thanks for the fast reply. I have tried to toggle with ‘\’ and I have also tried to tab in to the hex section and toggle with ‘t’.

Same issue. I attached a screenshot
![0550BDD5-A92C-4587-8C1A-FADD4E794F79](https://user-images.githubusercontent.com/20195547/62074786-59e9a180-b1f8-11e9-9fb1-64f8fd9f958f.jpeg)

Notice how the bottom section is blank?

I want to mention that it doesnt matter what frame I am on... that section is always blank.

**Comment by pocc** [comment]
Post the results of `tshark -v`

**Comment by inzel** [comment]
tshark -v
TShark (Wireshark) 2.4.2 (v2.4.2-0-gb6c63ae)

Copyright 1998-2017 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, with GLib 2.36.0,
with zlib 1.2.5, with SMI 0.4.8, with c-ares 1.12.0, with Lua 5.2.4, with GnuTLS
3.4.17, with Gcrypt 1.7.7, with MIT Kerberos, with GeoIP, with nghttp2 1.14.0,
with LZ4, with Snappy, with libxml2 2.9.4.

Running on Mac OS X 10.13.6, build 17G7024 (Darwin 17.7.0), with Intel(R)
Core(TM) i7-6920HQ CPU @ 2.90GHz (with SSE4.2), with 16384 MB of physical
memory, with locale en_US.UTF-8, with libpcap version 1.8.1 -- Apple version
79.20.1, with GnuTLS 3.4.17, with Gcrypt 1.7.7, with zlib 1.2.11.

Built using llvm-gcc 4.2.1 (Based on Apple Inc. build 5658) (LLVM build
2336.9.00)

**Comment by pocc** [comment]
While version 2.4 is technically still maintained, it is an older version. Would it be possible for you to upgrade wireshark to latest 3.0.x? You can do this with `brew cask reinstall wireshark`.

**Comment by inzel** [comment]
That did the trick! Awesome work on this tool man. Seriously impressed. I will be adding this tool to a training series I give so I expect many many more people will start using this very soon.

Thanks again!

**Comment by pocc** [comment]
Lol I'm only a contributor. Thank @gcla.

Cheers

**Comment by inzel** [comment]
Thanks @gcla :)
