### ISSUE TITLE
Ubuntu repository no longer working?

### ISSUE THREAD

**Issue by inzel** [gcla/termshark#51]
sudo add-apt-repository --update ppa:nicolais/termshark
 tag:launchpad.net:2008:redacted
 More info: https://launchpad.net/~nicolais/+archive/ubuntu/termshark
Press [ENTER] to continue or Ctrl-c to cancel adding it.

'Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0xtag:launchpad.net:2008:redacted: Not Found'

Anyone else experience this?

**Comment by pocc** [comment]
Gimme dat `tshark -v`

**Comment by inzel** [comment]
tshark -v
TShark (Wireshark) 2.6.8 (Git v2.6.8 packaged as 2.6.8-1~ubuntu18.04.0)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, with POSIX capabilities (Linux), with libnl 3,
with GLib 2.56.2, with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.14.0, with Lua
5.2.4, with GnuTLS 3.5.18, with Gcrypt 1.8.1, with MIT Kerberos, with MaxMind DB
resolver, with nghttp2 1.30.0, with LZ4, with Snappy, with libxml2 2.9.4.

Running on Linux 4.4.0-18362-Microsoft, with Intel(R) Core(TM) i9-8950HK CPU @
2.90GHz (with SSE4.2), with 32630 MB of physical memory, with locale C.UTF-8,
with libpcap version 1.8.1, with GnuTLS 3.5.18, with Gcrypt 1.8.1, with zlib
1.2.11, binary plugins supported (13 loaded).

Built using gcc 7.3.0.

========================================

Adding repository:
sudo add-apt-repository --update ppa:nicolais/termshark
 tag:launchpad.net:2008:redacted
 More info: https://launchpad.net/~nicolais/+archive/ubuntu/termshark
Press [ENTER] to continue or Ctrl-c to cancel adding it.

'Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0xtag:launchpad.net:2008:redacted: Not Found'

**Comment by inzel** [comment]
Ok, all updated.

TShark (Wireshark) 3.1.0 (Git Rev Unknown from unknown)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, with POSIX capabilities (Linux), with libnl 3,
with GLib 2.56.3, with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.14.0, with Lua
5.2.4, with GnuTLS 3.5.18 and PKCS #11 support, with Gcrypt 1.8.1, with MIT
Kerberos, with MaxMind DB resolver, without nghttp2, with brotli, with LZ4, with
Snappy, with libxml2 2.9.4.

Running on Linux 4.4.0-18362-Microsoft, with Intel(R) Core(TM) i9-8950HK CPU @
2.90GHz (with SSE4.2), with 32630 MB of physical memory, with locale C.UTF-8,
with libpcap version 1.8.1, with GnuTLS 3.5.18, with Gcrypt 1.8.1, with brotli
1.0.4, with zlib 1.2.11, binary plugins supported (0 loaded).

Built using gcc 7.3.0.

=====================================================

sudo add-apt-repository --update ppa:nicolais/termshark
 tag:launchpad.net:2008:redacted
 More info: https://launchpad.net/~nicolais/+archive/ubuntu/termshark
Press [ENTER] to continue or Ctrl-c to cancel adding it.

'Error reading https://keyserver.ubuntu.com/pks/lookup?op=get&options=mr&exact=on&search=0xtag:launchpad.net:2008:redacted: Not Found'

**Comment by inzel** [comment]
Checking for any updates

**Comment by pocc** [comment]
@NicolaiSoeborg do you have any insight into this? I'm getting the same error when attempting to add via the launchpad PPA with `sudo add-apt-repository ppa:nicolais/termshark`. My system is Ubuntu 18.04.

**Comment by inzel** [comment]
Thanks @pocc

**Comment by gcla** [comment]
Hi @inzel and @pocc - is this error still there for you both? I just tried it - Ubuntu 18.04 - and the PPA registered itself successfully.

**Comment by pocc** [comment]
Did @NicolaiSoeborg change something? Anyway, it's working for me now. @inzel can you check your system as well?

**Comment by inzel** [comment]
Appears to work now :)

**Comment by pocc** [comment]
Thanks for checking @inzel
