### ISSUE TITLE
Feature Request: Support for more wireshark pane views

### ISSUE THREAD

**Issue by thejerrod** [gcla/termshark#54]
I like the ability to switch layout/pane views, but the one I use the most is not there (layout order = pane 1 packet list, 2 packet details, 3 packet bytes)

I would like to see the current wireshark 3.x layout views scrollable with |, and configurable as a default display option in termshark.toml

<img width="733" alt="Screen Shot 2019-07-29 at 2 53 14 PM" src="https://user-images.githubusercontent.com/25254103/62085519-a3de8180-b210-11e9-8874-29c60d5d6675.png">

**Comment by pocc** [comment]
Thank you for the input @thejerrod. I'm marking this as a feature request.

**Comment by gcla** [comment]
Hi @thejerrod - I pushed a commit that does some of what you suggested:

- implements your preferred layout as one of the options that you can cycle through with '|'
- saves your chosen layout to termshark.toml

You can also hit +/- and </> to resize the panes relative to each other. Let me know what you think. Here's how to get the latest:

```bash
export GO111MODULE=on
git clone https://github.com/gcla/termshark
cd termshark
go install ./...
```

then termshark will be in `~/go/bin/`.

**Comment by gcla** [comment]
Please do re-open this if the commit above isn't enough. I'm doing some issue housekeeping.
