### ISSUE TITLE
Feature Request: Support wireshark coloring rules

### ISSUE THREAD

**Issue by thejerrod** [gcla/termshark#56]
Support for a wireshark coloring rule configuration file, to configure and support the wireshark coloring ruleset.

The default ruleset provides at-a-glance protocol and issue recognition. Being able to point to a config file where this exists on the filesystem allows us to import and share our existing wireshark coloring rulesets

> # DO NOT EDIT THIS FILE!  It was created by Wireshark
> @Bad TCP@tcp.analysis.flags && !tcp.analysis.window_update@[4626,10023,11822][63479,34695,34695]
> @HSRP State Change@hsrp.state != 8 && hsrp.state != 16@[4626,10023,11822][65535,64764,40092]
> @Spanning Tree Topology  Change@stp.type == 0x80@[4626,10023,11822][65535,64764,40092]
> @OSPF State Change@ospf.msg != 1@[4626,10023,11822][65535,64764,40092]
> @ICMP errors@icmp.type eq 3 || icmp.type eq 4 || icmp.type eq 5 || icmp.type eq 11 || icmpv6.type eq 1 || icmpv6.type eq 2 || icmpv6.type eq 3 || icmpv6.type eq 4@[4626,10023,11822][47031,63479,29812]
> @ARP@arp@[64250,61680,55255][4626,10023,11822]
> @ICMP@icmp || icmpv6@[64764,57568,65535][4626,10023,11822]
> @TCP RST@tcp.flags.reset eq 1@[42148,0,0][65535,64764,40092]
> @SCTP ABORT@sctp.chunk_type eq ABORT@[42148,0,0][65535,64764,40092]
> @TTL low or unexpected@( ! ip.dst == 224.0.0.0/4 && ip.ttl < 5 && !pim && !ospf) || (ip.dst == 224.0.0.0/24 && ip.dst != 224.0.0.251 && ip.ttl != 1 && !(vrrp || carp))@[42148,0,0][60652,61680,60395]
> @Checksum Errors@eth.fcs.status=="Bad" || ip.checksum.status=="Bad" || tcp.checksum.status=="Bad" || udp.checksum.status=="Bad" || sctp.checksum.status=="Bad" || mstp.checksum.status=="Bad" || cdp.checksum.status=="Bad" || edp.checksum.status=="Bad" || wlan.fcs.status=="Bad" || stt.checksum.status=="Bad"@[4626,10023,11822][63479,34695,34695]
> @SMB@smb || nbss || nbns || netbios@[65278,65535,53456][4626,10023,11822]
> @HTTP@http || tcp.port == 80 || http2@[58596,65535,51143][4626,10023,11822]
> @DCERPC@dcerpc@[51143,38807,65535][4626,10023,11822]
> @Routing@hsrp || eigrp || ospf || bgp || cdp || vrrp || carp || gvrp || igmp || ismp@[65535,62451,54998][4626,10023,11822]
> @TCP SYN/FIN@tcp.flags & 0x02 || tcp.flags.fin == 1@[41120,41120,41120][4626,10023,11822]
> @TCP@tcp@[59367,59110,65535][4626,10023,11822]
> @UDP@udp@[56026,61166,65535][4626,10023,11822]
> @Broadcast@eth[0] & 1@[65535,65535,65535][47802,48573,46774]
> @System Event@systemd_journal || sysdig@[59110,59110,59110][11565,28527,39578]

**Comment by gcla** [comment]
This is a cool idea - I've slated it for v3 once I get v2 out.

**Comment by pocc** [comment]
Good for you! It's always good to make changes incrementally and scope small.

Is there a feature list for v2? If it's coming out soon I guess it's immaterial.

**Comment by gcla** [comment]
Hi - I made link from termshark.io to point to the staged ChangeLog. This is in the branch v2docs which I'll merge back when I push out v2. Here's the link: https://termshark.io/changelog

**Comment by gcla** [comment]
Hi @thejerrod - do you have a few minutes to try a prototype of this feature? You can get the binary with packet coloring using this command:

```bash
go get github.com/gcla/termshark/v2/cmd/termshark@bb4213ad
```

(I'm using Go 1.13 fwiw, with `export GO111MODULE=on`)

If the default `tshark` binary supports packet-coloring, then it should *just work*, using your packet coloring rules from Wireshark (`/usr/share/wireshark/colorfilters` and probably `~/.wireshark/colorfilters`). Termshark tries to make sure `tshark` supports the `--color` flag before it turns on color. The accuracy of the colors depend on your terminal. If your terminal supports truecolor, then they should be perfect; if it supports 256 colors, then close; if only 8 colors, then very approximate :-) I use gnome-terminal typically, and have tried with each of

`export TERM=screen-truecolor`
`export TERM=screen-256color`
`export TERM=screen`    (8 colors)

Here's a screenshot in a 256 color terminal window using these rules: https://wiki.wireshark.org/General_use_ColorFilter

![image](https://user-images.githubusercontent.com/45680/69001639-5dd92680-08b0-11ea-84ca-739fcd9ebd7d.png)

**Comment by gcla** [comment]
I'm going to close this issue just to tidy up. I'll include this feature in the next release announcement.
