### ISSUE TITLE
Bind shortcut key for apply button 

### ISSUE THREAD

**Issue by rongyi** [gcla/termshark#6]
hit enter in filter input is noop. How about when input is valid we do apply button callback?

**Comment by pocc** [comment]
To clarify this is to hit the `<apply>` field after entering a display filter.

This feature would be valuable for me too. Default for Wireshark is `<return>`, so that's a good candidate here too.

**Comment by rongyi** [comment]
@pocc yes, exactly as you said.

**Comment by gcla** [comment]
Thanks for the suggestion, I'll do this.

**Comment by gcla** [comment]
Hi @rongyi  - sorry it's been such a long time. I finally pushed a change that tries to fix this. If you'd like to try it, it's in the master branch, or here's a link to a linux/amd64 binary:

https://storage.googleapis.com/termshark/de7bc2d3d38328dc95981edd3223c7b2ac908b98/termshark_linux_amd64/termshark

**Comment by gcla** [comment]
Thanks, I'll close this issue.
