### ISSUE TITLE
high ram usage when loading small pcap file

### ISSUE THREAD

**Issue by cmosig** [gcla/termshark#62]
### Problem 
I am loading a very tiny pcap file (11 packets) with termshark. 

### Current Behavior

When using using the mouse, clicking and scrolling, the ram usage is up at 20 to 30 GB within seconds.

### Expected Behavior

I am not sure how much ram termshark should consume. 

### Screenshots as applicable 
(I cut out the IPs) 
![2019-09-19-154821_3840x2160_scrot](https://user-images.githubusercontent.com/32590522/65250333-b3ce5f80-daf5-11e9-8e0f-7322f2244c19.png)

### Steps to Reproduce

1. open a small file
2. click or scroll anywhere

## Context

Please provide the complete output of these commands:

* Wireshark Version (tshark -v):
```
TShark (Wireshark) 3.0.3 (Git commit 6130b92b0ec6)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, with POSIX capabilities (Linux), with libnl 3,
with GLib 2.60.5, with zlib 1.2.11, without SMI, with c-ares 1.15.0, with Lua
5.2.4, with GnuTLS 3.6.8 and PKCS #11 support, with Gcrypt 1.8.4, with MIT
Kerberos, with MaxMind DB resolver, with nghttp2 1.36.0, with LZ4, with Snappy,
with libxml2 2.9.9.

Running on Linux 4.19.69-1-MANJARO, with        Intel(R) Xeon(R) CPU E5-1620 0 @
3.60GHz (with SSE4.2), with 19988 MB of physical memory, with locale
LC_CTYPE=en_GB.UTF-8, LC_NUMERIC=de_DE.UTF-8, LC_TIME=de_DE.UTF-8,
LC_COLLATE=en_GB.UTF-8, LC_MONETARY=de_DE.UTF-8, LC_MESSAGES=en_GB.UTF-8,
LC_PAPER=de_DE.UTF-8, LC_NAME=de_DE.UTF-8, LC_ADDRESS=de_DE.UTF-8,
LC_TELEPHONE=de_DE.UTF-8, LC_MEASUREMENT=de_DE.UTF-8,
LC_IDENTIFICATION=de_DE.UTF-8, with libpcap version 1.9.0-PRE-GIT (with
TPACKET_V3), with GnuTLS 3.6.9, with Gcrypt 1.8.5, with zlib 1.2.11, binary
plugins supported (0 loaded).

Built using gcc 9.1.0
```
* Termshark Version (termshark -v):
```
termshark v1.0.0++
```

Please also provide any relevant information about your environment (OS, VM, pi,...):
Manjaro Linux 18.1.0

**Comment by pocc** [comment]
Hi Clemens,

I REALLY appreciate the effort you put into making this issue. This is very well written. Unfortunately, this is the same issue as #61, and so I need to close as duplicate.

**Comment by gcla** [comment]
Thank you @cmosig from me too. I see the same issue, especially on a low-end system like a raspberry pi. It seems to me that I've made termshark cause an enormous amount of small memory allocations, and these are largely the cause... Not sure why I haven't noticed before. Thinking about a solution...

**Comment by cmosig** [comment]
No problem. I saw #61, but I thought that issue was about high cpu utilization not ram. Then nvmd :)

**Comment by gcla** [comment]
Hi @cmosig - turns out both are linked. Would you mind trying the instructions in #61? I think the problem is an event backlog when the mouse is moving a lot. Let me know!

**Comment by cmosig** [comment]
Sorry, for the late reply. I was out of town..

Using this binary...
https://github.com/gcla/termshark/issues/61#issuecomment-535735966
...the really high ram usage seems to be fixed. Thanks!
Still termshark uses about 500MB (after interacting with the mouse) showing a pcap file with 11 lines.. It's okay, but it seems a lot.

**Comment by gcla** [comment]
Hi @cmosig - is that 500MB the VM usage or RSS? Can you tell if it goes higher still if you load a larger pcap? 

Wonder if this is related: https://golang.org/doc/go1.12#runtime

**Comment by cmosig** [comment]
Its RSS. 
Loading smallFlows.pcap from
http://tcpreplay.appneta.com/wiki/captures.html
... and using the mouse, ram usage goes up to about 3GB
Loading bigFlows.pcap and using the mouse, ram usage goes up to about 2G. Yes, the bigger file used less ram. Don't ask me why. I performed similar "mouse movements" in both instances.

I guess this is "fixed". :)
