### ISSUE TITLE
termux binary doesn't run on Android Q

### ISSUE THREAD

**Issue by gcla** [gcla/termshark#63]
Seems related to this:

https://github.com/syncthing/syncthing-android/issues/1291

and may just need to be compiled with go 1.13:

https://github.com/golang/go/issues/29674

**Comment by gcla** [comment]
I've opened this against termux-root-packages: https://github.com/termux/termux-root-packages/issues/132

**Comment by ghost** [comment]
Termux binaries are built and published by @Grimler91. He just need to rebuild it or I can do this.

**Comment by gcla** [comment]
Thanks @xeffyr - termshark runs again on android :-)
