### ISSUE TITLE
regression on option 't'

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#67]
## Prerequisites

- Running v2 candidate 2a5d55c0a9b826e74213a8c1937a7c16d8e8aa9e

### Current Behavior

Pressing `t` when in bytes view does nothing.

### Expected Behavior

Per onscreen docs, `'t' - In bytes view, switch between hex <-> ascii`

### Screenshots as applicable 

<img width="548" alt="Screen Shot 2019-11-08 at 1 38 39 PM" src="https://user-images.githubusercontent.com/10995145/68512400-2540a980-022d-11ea-9690-f6344394adb2.png">

### Steps to Reproduce

1. `mbp:termshark rj$ go run cmd/termshark/termshark.go`
2. Tab twice to bytes pane
3. Hitting 't' does nothing

## Context

Note: Have not tested on other OSes/devices

OS: Macos 10.14, laptop

Tshark:

```
mbp:termshark rj$ go run cmd/termshark/termshark.go -v | cat
TShark (Wireshark) 3.0.3 (v3.0.3-0-g6130b92b0ec6)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, with GLib 2.37.6,
with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.15.0, with Lua 5.2.4, with
GnuTLS 3.4.17, with Gcrypt 1.7.7, with MIT Kerberos, with MaxMind DB resolver,
with nghttp2 1.21.0, with LZ4, with Snappy, with libxml2 2.9.9.

Running on Mac OS X 10.14.6, build 18G103 (Darwin 18.7.0), with Intel(R)
Core(TM) i7-4770HQ CPU @ 2.20GHz (with SSE4.2), with 16384 MB of physical
memory, with locale en_US.UTF-8, with libpcap version 1.8.1 -- Apple version
79.250.1, with GnuTLS 3.4.17, with Gcrypt 1.7.7, with zlib 1.2.11, binary
plugins supported (0 loaded).

Built using clang 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4).
```

**Comment by gcla** [comment]
Thanks. I took it away when I rewrote the hexdumper - I figured it wasn't that useful, since you'd probably want the cursor position in both the byte and ascii views to be the same. I've fixed the UserGuide in the v2 branch to remove the reference to that keypress, as you suggested. And yes, I'll find out soon if anyone misses the toggle when v2 ships :-)
