### ISSUE TITLE
termshark display broken on terminal multiplexer

### ISSUE THREAD

**Issue by punkymaniac** [gcla/termshark#7]
The worst thing is the invisible cursor.

On screen:
![screen](https://user-images.githubusercontent.com/9916797/56569216-d72dc680-65b8-11e9-8e3c-7fdd396b5a58.png)
On tmux:
![tmux](https://user-images.githubusercontent.com/9916797/56569226-db59e400-65b8-11e9-81c3-aacdd03e6d68.png)

**Comment by gcla** [comment]
That's no good, sorry :( I've been using tmux exclusively, so I'll give screen a try. Out of interest, does your terminal emulator support more than monochome? If so, it might work better if you change TERM e.g.

export TERM=screen

or even

export TERM=screen-256color

**Comment by punkymaniac** [comment]
My TERM variable is already set to screen-256color.
I use xfce4-terminal or Terminator on centos7 but still have the issue on both of them.

Also, I don't set GO111MODULE=on before go get.
Because when I set it I have a nearly problem as describe here [https://github.com/golang/go/issues/26639](https://github.com/golang/go/issues/26639)
Could be this ??

**Comment by pocc** [comment]
This is a problem with tcell. I've verified this by finding another tcell-based project (browsh), and I see the same broken lines when using screen. browsh works fine otherwise.
<img width="1139" alt="Screen Shot 2019-06-11 at 8 54 12 PM" src="https://user-images.githubusercontent.com/10995145/59298575-1c05dd80-8c8b-11e9-80bc-61b360fc95bc.png">

**Comment by gcla** [comment]
Hi @punkymaniac - the author of tcell has fixed this problem, and I've updated termshark's dependency to use tcell latest. Would you mind trying termshark again? To build the latest, try this

```bash
git clone https://github.com/gcla/termshark
cd termshark
export GO111MODULE=on
go install ./...
```

Then termshark will be in `~/go/bin/`. Let me know!

**Comment by gcla** [comment]
I think this is resolved, but please do re-open if the problem remains.
