### ISSUE TITLE
Ctrl+W does not clear screen

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#70]
## Prerequisites

- Running v2 candidate 2a5d55c0a9b826e74213a8c1937a7c16d8e8aa9e

### Current Behavior

Hitting Ctrl+W does nothing.

### Expected Behavior

Hitting Ctrl+W removes current packets. This does work if you click on Misc > Clear Packets. 

### Screenshots as applicable 

NA - nothing happens on keypresses

### Steps to Reproduce

1. `mbp:termshark rj$ go run cmd/termshark/termshark.go`
2. Hit Ctrl+W during a live capture
3. Stare into the void
4. Observe lack of response

## Context

Note: Have not tested on other OSes/devices

OS: Macos 10.14, laptop

Tshark:

```
mbp:termshark rj$ go run cmd/termshark/termshark.go -v | cat
TShark (Wireshark) 3.0.3 (v3.0.3-0-g6130b92b0ec6)

Copyright 1998-2019 Gerald Combs <gerald@wireshark.org> and contributors.
License GPLv2+: GNU GPL version 2 or later <http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with libpcap, without POSIX capabilities, with GLib 2.37.6,
with zlib 1.2.11, with SMI 0.4.8, with c-ares 1.15.0, with Lua 5.2.4, with
GnuTLS 3.4.17, with Gcrypt 1.7.7, with MIT Kerberos, with MaxMind DB resolver,
with nghttp2 1.21.0, with LZ4, with Snappy, with libxml2 2.9.9.

Running on Mac OS X 10.14.6, build 18G103 (Darwin 18.7.0), with Intel(R)
Core(TM) i7-4770HQ CPU @ 2.20GHz (with SSE4.2), with 16384 MB of physical
memory, with locale en_US.UTF-8, with libpcap version 1.8.1 -- Apple version
79.250.1, with GnuTLS 3.4.17, with Gcrypt 1.7.7, with zlib 1.2.11, binary
plugins supported (0 loaded).

Built using clang 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4).
```

**Comment by gcla** [comment]
hi - thanks for this, and you're right. The way I set it up, ctrl-w is scoped to the open menu. Is that lame? It might be lame :-/ So you have to hit Esc then ctrl-w. Let me know, I can promote the key capture to the main UI...

**Comment by pocc** [comment]
Yeah I think that while it's cool that you're adding features, you're adding needless (and confusing) complexity by having two different keyboard shortcut scopes.

**Comment by gcla** [comment]
Thanks, now fixed in master.
