### ISSUE TITLE
failed to run on ubuntu 18.04

### ISSUE THREAD

**Issue by laoshaw** [gcla/termshark#71]
Just downloaded 2.0.0 and did a quick run with `sudo termshark` here is what I got:

```
sudo termshark
(The termshark UI will start when packets are detected...)
Error running command [command: /usr/bin/dumpcap [dumpcap -P -i wlp2s0 -w /home/w45g/.cache/termshark/pcaps/wlp2s0--2019-11-15--08-52-02.pcap], error: exit status 1]
```

**Comment by laoshaw** [comment]
ok without using "sudo"  and run it as root directly it works.

**Comment by pocc** [comment]
Thanks for raising an issue and providing a solution!

**Comment by alicektx** [comment]
...of whatever future help to whomever, 
the following worked flawlessly under older Ubuntu 16.04 (Xenial).
I assume the same would be the case for 18.04 Bionic or latter versions...

wget https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz
tar zxvf go1.13.4.linux-amd64.tar.gz
cd go/
mkdir var
export GOROOT=$HOME/go
export GOPATH=$HOME/go/var
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
export GO111MODULE=on
CGO_ENABLED=0 go get -ldflags="-s -w" github.com/gcla/termshark/v2/cmd/termshark@master
sudo cp var/bin/termshark /usr/local/sbin/termshark
sudo apt-get install --no-install-recommends tshark
sudo gpasswd -a $USER wireshark
sudo setcap cap_dac_override,cap_net_admin,cap_net_raw+eip /usr/bin/dumpcap
Log-out & log-in back for the changes to take effect...

Summary...
1) Grabbed & extracted latest stable Golang...currently 1.13.4, 
and temporarily set the proper enviroment variables...
2) Built a nice static & portable binary from the latest master... 
(not much of a Snap/Flatpak fan myself...
and especially with Go programs, what for...nah...) ;-)
3) Installed tshark, added current user to the wireshark group, 
and set proper permissions for such to be able to capture packets,
without sudo / being root etc...

On another note - this has to be one of the coolest tui programs ever :+1:

**Comment by gcla** [comment]
Thanks @alicektx, your comment made my day :-)
