### ISSUE TITLE
Tail type mismatch

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#72]
## Problem 

Some process is expecting `*"github.com/hpcloud/tail/vendor/gopkg.in/tomb.v1"`.Tomb, but getting `*"github.com/gcla/tail/vendor/gopkg.in/tomb.v1".Tomb` 

### Current Behavior

Attempt to install with go get, there's a tail error
$ go get github.com/gcla/termshark
# github.com/gcla/tail
../../go/src/github.com/gcla/tail/tail.go:188:45: cannot use &tail.Tomb (type *"github.com/gcla/tail/vendor/gopkg.in/tomb.v1".Tomb) as type *"github.com/hpcloud/tail/vendor/gopkg.in/tomb.v1".Tomb in argument to tail.watcher.BlockUntilExists
../../go/src/github.com/gcla/tail/tail.go:327:49: cannot use &tail.Tomb (type *"github.com/gcla/tail/vendor/gopkg.in/tomb.v1".Tomb) as type *"github.com/hpcloud/tail/vendor/gopkg.in/tomb.v1".Tomb in argument to tail.watcher.ChangeEvents

### Expected Behavior

Installation processes normally for latest commit.

### Screenshots as applicable 

NA

### Steps to Reproduce

1. Delete current termshark installation with `rm -rf ~/go/src/github.com/gcla/termshark`
2. Attempt to reinstall with `go get github.com/gcla/termshark`

## Context

Macos 10.14, tshark version 3.03, termshark version is 2.0.1+ (latest commit)

**Comment by pocc** [comment]
Looks like this is the same problem that @mharic reported in #34.

**Comment by gcla** [comment]
Hi - yes, there's a new change to the command to do this, but I didn't understand that would be the case when I decided to make termshark v2... Please could you try this for the latest tagged version (2.0.2 as I write this):

```bash
go get github.com/gcla/termshark/v2/cmd/termshark
```

and this for the latest in the master branch (`termshark -v` should report v2.0.2++)

```bash
go get github.com/gcla/termshark/v2/cmd/termshark@master
```

I'm using Go 1.13 locally with `GO111MODULE=on`. Let me know how that goes. I've adjusted the instructions in README.md.

**Comment by gcla** [comment]
Please do re-open if the problem remains.
