### ISSUE TITLE
Termshark v2.0.0 has problems rendering on Windows

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#73]
## Problem 

Termshark crashes on Windows 10. Stderr indicates some form of widget error. Full log is attached: [error.zip](https://github.com/gcla/termshark/files/3947966/error.zip) and also at https://pastebin.com/RF9UpjP3. Main error is below for search:

```sh
.\Downloads\termshark.exe : panic: All columns widgets were rendered Max, so there is no max height to use.
At line:1 char:1
+ .\Downloads\termshark.exe -i 2 2> out.txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (panic: All colu... height to use.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

### Current Behavior

Termshark will open briefly and then crash (and annoyingly closes the terminal that it was run in)

### Screenshots as applicable 

Right before crash:
<img width="341" alt="Screen Shot 2019-12-10 at 5 42 17 PM" src="https://user-images.githubusercontent.com/10995145/70584039-80d7bd00-1b74-11ea-80a6-65b51e622dab.png">

### Steps to Reproduce

Open termshark from Powershell with `termshark -i <default interface>`

## Context

Windows 10 VM

```sh
PS C:\Users\rj> .\Downloads\termshark.exe -vv
termshark v2.0.0
using tshark 3.0.0 (from C:\Program Files\Wireshark\tshark.exe)
```

**Comment by gcla** [comment]
Oof... Thanks for the terrific-as-always bug report, I'll look into this

**Comment by pocc** [comment]
Cheers - you approved my bug report format so you deserve some credit too!

**Comment by gcla** [comment]
Hi @pocc - when you get a free 5 minutes, could you try out a binary based on the commit above? Something like this

```bash
export GO111MODULE=on
git clone https://github.com/gcla/termshark
cd termshark
git pull # including 2978a06
GOOS=windows GOARCH=amd64 go install ./...
```

then the binary should be `~/go/bin/windows_amd64/termshark.exe`

Thanks :-)

**Comment by pocc** [comment]
Confirmed resolved. Thanks for the quick resolution!

### Side note 

`export` and `GOOS/GOARCH` don't register as keywords in powershell. You need to do something like this instead (see [so question](https://stackoverflow.com/questions/20829155/how-to-cross-compile-from-windows-to-linux)) to set GOOS and GOARCH:

```powershell
set GOARCH=amd64
set GOOS=windows
```

In this case it didn't matter though because it defaulted to native arch and os.
