### ISSUE TITLE
Support for multiple network interfaces

### ISSUE THREAD

**Issue by IAXES** [gcla/termshark#75]
It would be very helpful to be able to support capture and rendering for multiple network interfaces concurrently, similar to the Windows GUI for Wireshark. I can specify multiple interfaces like so:

```
termshark -i eth0 -i eth1 -i eth2
```

This appears to pass the correct options to `dumpcap`, but `termshark` only renders data for the final/last interface specified in this manner (in this case, `eth2`). I can always start multiple instances and hop between them rapidly in `tmux`, but being able to view interleaved packets from multiple interfaces in a single instance would be very helpful.

**Comment by pocc** [comment]
Thanks for the feature request! In the interim, this should by possible by using a FIFO:

```bash
mkfifo mypipe
dumpcap -i 2 -i 5 -w mypipe & termshark -r mypipe
```

**Comment by gcla** [comment]
I didn't know wireshark could do that :-0

**Comment by gcla** [comment]
Hi - I've just pushed a change to provide a prototype of this feature. It was slightly trickier than I thought it would be at first, so I've checked it in to a branch, for now, in case there are problems I've missed. If you have a few minutes to try it out, that'd be great :) I think this ought to install it:

```bash
export GO111MODULE=on
go get github.com/gcla/termshark/v2/cmd/termshark@multipleinterfaces
```

Here's the commit, for reference: https://github.com/gcla/termshark/commit/2f82bd264ee58a92f08ddc94335439f8bb891de2

These commands should be possible now:

```
termshark -i eth0 -i eth1
cat foo.pcap | termshark -i - -i eth0
mkfifo fifo
cat foo.pcap > fifo &
termshark -i fifo -i eth0
```

**Comment by gcla** [comment]
I've merged this to master. Please let me know if anything isn't working as you'd expect...

I'll close this for now.
