### ISSUE TITLE
Build code from gcla/tail only on Windows to allow Debian packaging

### ISSUE THREAD

**Issue by gcla** [gcla/termshark#76]
This is related to #74.

If we can ensure code from gcla/tail is only compiled on Windows (the only target for which it's needed), then gcla/tail won't need to be packaged for Debian, meaning termshark's Debian package can be updated.

CCing @dawidd6

**Comment by dawidd6** [comment]
Can I try?

**Comment by gcla** [comment]
Yeah absolutely, thanks! I'll assign it to you
