### ISSUE TITLE
Why is a shark fin blocking the screen?

### ISSUE THREAD

**Issue by pbksol** [gcla/termshark#83]
Why?

<img width="1404" alt="Bildschirmfoto 2020-02-20 um 10 41 50" src="https://user-images.githubusercontent.com/8238713/74930910-db945d00-53de-11ea-96ca-2f26cd07e835.png">

**Comment by gcla** [comment]
Guilty as charged

I am going to err on the side of caution and assume you really don't want it there, in which case, first - apologies :( - and second - add this to `~/.config/termshark/termshark.toml`

```
[main]
  disable-shark-fin = true
```

**Comment by pbksol** [comment]
Thanks.
But what is the fin supposed to do? My first impression was it's some kind of "I'm still there, waiting for things to happen" – some kind of load animation or so. But in this case it was blocking filtered content and that was the odd part.

**Comment by pocc** [comment]
Was it blocking filtered content after you moved your mouse or pressed a key? This iteration of the sharkfin should disappear on user interaction.

**Comment by pbksol** [comment]
Exactly. It kept moving with the filter shown and even after expanding the protocol/frame details (the [+] part). That was unexpected and the data a bit hard to read ;-)

**Comment by pocc** [comment]
Sorry to hear - this sounds more like a bug. It shouldn't be doing this. Thank you for making this issue!

**Comment by gcla** [comment]
Yes, that has backfired. I'll take a look asap. It's supposed to appear only after 30s of no user input when loading packets from a live capture, and then disappear as soon as there is user input. To answer your question about its purpose - just for fun really.

**Comment by pocc** [comment]
> Exactly. It kept moving with the filter shown and even after expanding the protocol/frame details (the [+] part). That was unexpected and the data a bit hard to read ;-)

I think @pbksol was asking why the sharkfin was locking the UI, not why it was there. For what it's worth, I think it's fun :-)
