### ISSUE TITLE
Make it easier to provide feedback

### ISSUE THREAD

**Issue by pocc** [gcla/termshark#84]
### Problem

There's no "I found a bug" or "Feature Request" buttons in the Misc menu. Making them easier to access will encourage people to use them. For point of comparison, Chrome has a "Create an issue..." under their Help menu on Macos.

### Describe the solution you'd like

Add 2 menu items with these links:

* bug report: https://github.com/gcla/termshark/issues/new?assignees=&labels=&template=bug_report.md&title=
* feature request: https://github.com/gcla/termshark/issues/new?assignees=&labels=&template=feature_request.md&title=

### Describe alternatives you've considered

People could look up the repo and find issues like they currently do?

### Additional context

It would probably go under FAQ, but neither of these would need their own shortcut.

---

Thoughts?

**Comment by gcla** [comment]
Excellent idea
