### ISSUE TITLE
Termshark throws an error when opened

### ISSUE THREAD

**Issue by basondole** [gcla/termshark#92]
## Prerequisites

- [x] I am running the latest versions of Termshark and Wireshark.
- [x] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [x] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

### Current Behavior

When running termshark the window opens and shows an error
```
Error running command                                                                                                                         
command: /usr/sbin/tshark [tshark -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i" -i - -l]     
error: exit status 1 
```
### Expected Behavior

See packets being captured

### Screenshots as applicable 

* I do not have screenshot of good expected state
* Problem state.
![image](https://user-images.githubusercontent.com/50369643/90329178-0e449a00-dfab-11ea-9804-cbb12a0028ba.png)

### Steps to Reproduce

1. Launch termshark on cli `$ termshark -i ens160`
2. See error

## Context

* termshark -v (or termshark -vv if running from git/HEAD)
```
$ termshark -v
termshark v2.1.1
```
* termshark -v | cat
```
$ termshark -v | cat
TShark 1.10.14 (Git Rev Unknown from unknown)

Copyright 1998-2015 Gerald Combs <gerald@wireshark.org> and contributors.
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiled (64-bit) with GLib 2.56.1, with libpcap, with libz 1.2.7, with POSIX
capabilities (Linux), without libnl, with SMI 0.4.8, with c-ares 1.10.0, with
Lua 5.1, without Python, with GnuTLS 3.3.29, with Gcrypt 1.5.3, with MIT
Kerberos, without GeoIP.

Running on Linux 3.10.0-1062.12.1.el7.x86_64, with locale en_US.UTF-8, with
libpcap version 1.5.3, with libz 1.2.7.
      Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz

Built using gcc 4.8.5 20150623 (Red Hat 4.8.5-39).
```

```
$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
```

**Comment by gcla** [comment]
Thanks for the report @basondole , I'll investigate

**Comment by gcla** [comment]
Hi @basondole - please could you try this termshark binary?

https://storage.googleapis.com/termshark/9800dd4749a527b5e7cd8792fb8c551e754399a3/termshark_linux_amd64/termshark

Just download and drop it somewhere in PATH, ahead of the one you have installed.

**Comment by basondole** [comment]
Hello,

Does this mean I dont have to remove the current installation I did via `$ install termshark`

Regards
Paul SIB

**Comment by gcla** [comment]
Hi @basondole - yes, you can try out the binary without removing the version you have installed. Termshark itself is really only one file - the executable. I suspect your installer will put the official version of termshark somewhere standard like `/usr/bin`. So maybe you could either 

(a) copy the one in the link above to `/usr/local/bin` and make sure `/usr/local/bin` is ahead of `/usr/bin` in PATH, or
(b) just run termshark directly from the download directory e.g. `$ ~/Downloads/termshark -i ens160`

**Comment by basondole** [comment]
Hello
I just replaced the earlier install by copying the binary to `/usr/local/bin`
Works fine now, thank you so much @gcla
