### ISSUE TITLE
Feature Request: Support "Go to packet" function

### ISSUE THREAD

**Issue by loudsong** [gcla/termshark#93]
In Wireshark, you can browse to a specified frame number using ctrl-g or menu item "Go > Go to Packet..." I'd like to see this feature implemented in Termshark.

I tried using a display filter as a possible workaround. I can give it "frame.number eq 10130" which filters down to the given packet only. But I want to browse to the packet and see the other packets surrounding it. If I then try to clear the display filter, it takes me back to frame 1 (instead of leaving me at frame 10130, where I wanted the view to remain.)

Without this, it makes it difficult to view a specific section of a large, unfiltered, capture file.

**Comment by pocc** [comment]
This is possible with v3. Take [a look](https://github.com/gcla/termshark/issues/26).

**Comment by gcla** [comment]
Hi @loudsong - are the features in the link above sufficient, do you think? Let us know. I'll leave this open for a few more days.

**Comment by loudsong** [comment]
Hi @gcla. Yes, it seems sufficient. Being able to go to a specific frame with, say `10130gg`, solves my problem. Thanks!

**Comment by gcla** [comment]
Thanks @loudsong , I'll close this issue.
