### ISSUE TITLE
Disable arrow cross panes

### ISSUE THREAD

**Issue by kevinhwang91** [gcla/termshark#94]
### Is your feature request related to a problem? Please describe.

When I use `up` and `down` will across the other pane, it's so annoying.

### Describe the solution you'd like
Only use `tab` and `s-tab` to switch the pane

**Comment by gcla** [comment]
Hi @kevinhwang91 - thanks for the report. I agree and I thought I'd disabled switching panes with the arrows - but I just noticed that if you are using the non-default layout, my fixes don't work :-( Sorry. I'll fix this after work this evening.

**Comment by kevinhwang91** [comment]
Thanks. I'm also waiting for your patch for vim key binding!

**Comment by gcla** [comment]
Hi @kevinhwang91 - please could you try a binary from the list below and let me know how it goes? Btw, am I right in guessing you  typically use layout (2) or (3) below, and not (1)?

```
       	       	 (1)   	       	       	       	   (2) 	       	       	       	    (3)
   						     						  
      +------------------------+       +------------------------+	+------------+-----------+
      |        	               |       |                        |	|            |           |
      |        	               |       |                        |	|            |           |
      |------------------------|       |                        |	|            |           |
      |                        |       |------------+-----------|	|------------|           |
      |                        |       |            |           |	|            |           |
      |------------------------|       |            |           |	|            |           |
      |                        |       |            |           |	|            |           |
      |                        |       |            |           |	|            |           |
      +------------------------+       +------------+-----------+      	+------------+-----------+
```

Linux: https://storage.googleapis.com/termshark/bf985811d0388c8050ca023f01822f8375e24e9d/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/bf985811d0388c8050ca023f01822f8375e24e9d/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/bf985811d0388c8050ca023f01822f8375e24e9d/termshark_windows_amd64/termshark.exe

(If you want to build from source, the code is in the `tabbetweenpanes` branch)

**Comment by gcla** [comment]
Oh I should also mention - this is branched from master which contains the vim-keys work too, if you'd like to try it. Hit the ':' key to start, then there are various help commands from there. Feedback most welcome! I am hoping to do a 2.2 release very soon once I can nail down the configurable table columns and after an imminent work deadline.

**Comment by kevinhwang91** [comment]
The patch works for three layouts as expected.

**Comment by kevinhwang91** [comment]
After patching, I think package details pane should add key binding `left` for collapse and `right` for expansion.
