### ISSUE TITLE
Resume Auto Scroll on Interface Captures

### ISSUE THREAD

**Issue by jboverfelt** [gcla/termshark#96]
### Is your feature request related to a problem? Please describe.

When I capture off an interface, the default behavior is that Termshark autoscrolls and keeps the most recent packet at the bottom of the window. This is in keeping with what I'm used to in Wireshark. However, if I move up using the up arrow to investigate a packet, I'd like a way to get back to the "autoscroll so most recent packet is always at the bottom" starting behavior. In Wireshark, I'm able to do this by scrolling to the bottom of the window.

### Describe the solution you'd like
I would like to be able to hit the "End" key or similar to "go live" again after investigating a packet during a live capture. It could really be any key combo provided the combination is documented in the help window.

### Describe alternatives you've considered
Having two windows open, one "live" and the other for investigation is a possible workaround but is not ideal and still requires killing one of the termshark instances repeatedly if multiple packets need to be investigated in the course of a session.

**Comment by gcla** [comment]
Thanks @jboverfelt , this is a good idea and should be straight-forward to implement. I'll look into it.

**Comment by kevinhwang91** [comment]
I also desire this feature.

**Comment by gcla** [comment]
Hi @jboverfelt and @kevinhwang91 - I've made a change in the main branch that will make termshark resume auto-scrolling during the current capture if you hit the end key in the packet list view. Let me know if this is suitable for you :-)

Linux: https://storage.googleapis.com/termshark/7e07a52207d2a2e72cdd453eee6360bc350151d2/termshark_linux_amd64/termshark

macOS: https://storage.googleapis.com/termshark/7e07a52207d2a2e72cdd453eee6360bc350151d2/termshark_darwin_amd64/termshark

Windows: https://storage.googleapis.com/termshark/7e07a52207d2a2e72cdd453eee6360bc350151d2/termshark_windows_amd64/termshark.exe

**Comment by kevinhwang91** [comment]
It works as expected, but binding `G` like vim behavior is better at the same time.

**Comment by jboverfelt** [comment]
Seems to work as expected - thanks for the quick turnaround on this!

**Comment by jboverfelt** [comment]
Seems to work as expected - thanks for the quick turnaround on this!

**Comment by gcla** [comment]
> It works as expected, but binding `G` like vim behavior is better at the same time.

Good idea - I've added that too, Linux build here:

https://storage.googleapis.com/termshark/796f4cf17b345a1de0b1e2eec18f41e865dc348d/termshark_linux_amd64/termshark

**Comment by kevinhwang91** [comment]
work as expected. I think it's time to close this issue.
