### ISSUE TITLE
5037 port is used while capturing the packages in the loopback interface.

### ISSUE THREAD

**Issue by kevinhwang91** [gcla/termshark#98]
## Prerequisites

Please verify these before submitting an issue.

- [x] I am running the latest versions of Termshark and Wireshark.
- [x] I checked the [README](https://github.com/gcla/termshark) and [User Guide](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md) and found no answer
- [x] I searched [issues](https://github.com/gcla/termshark/issues?q=is%3Aissue) and this has not yet been filed

## Problem 
5037 port is used while capturing the packages in the loopback interface.

### Current Behavior
5037 port always be used while capturing.

### Expected Behavior
5037 port never show while capturing.

### Screenshots as applicable 

![image](https://user-images.githubusercontent.com/17562139/94469363-95b33900-01f8-11eb-8dc6-092a8f8ec1a6.png)

### Steps to Reproduce

1. Run `termshark -i lo`, 5037 port is always captured.
2. Run `sudo tcpdump -i lo` at the same time, which also captured the 5037 port.
3. Close `termshark` process.
4. 5037 port never show again in stdout of `tcpdump`.

## Context

Please provide the complete output of these commands:

* termshark -v (or termshark -vv if running from git/HEAD)
* termshark -v | cat
```
termshark v2.1.2
using tshark 3.2.7 (from /usr/bin/tshark)
```

OS: `ArchLinux`

**Comment by gcla** [comment]
Thanks @kevinhwang91 , I can reproduce this. No idea what it is at the moment. More soon!

**Comment by gcla** [comment]
Hi @kevinhwang91 - could you try the following:

```
shell1$ tshark -i lo
shell2$ tshark -r /some/pcap/you/have.pcap
```

Do you see the port 5037 traffic when you start the tshark command in shell2?

I managed to capture it in action on my own machine:

```
gcla     2752007 26.0  0.1 1829328 48692 pts/18  Sl+  00:53   0:00  |   |       \_ termshark -i lo --debug
gcla     2752053  0.0  0.3 769428 113516 pts/18  Sl   00:53   0:00  |   |           \_ tshark -T psml -o gui.column.format:"No.","%m","Time","%t","Source","%s","Destination","%d","Protocol","%p","Length","%L","Info","%i" -r - -l -d udp.port==2075,cflow -d udp.port==9191,cflow -d udp.port==2055,cflow -d udp.port==2095,cflow
gcla     2752108  0.0  0.0   6832  2396 pts/18   S    00:53   0:00  |   |           |   \_ bash /usr/lib/x86_64-linux-gnu/wireshark/extcap/androiddump --extcap-interfaces --extcap-version=3.2
```

Wireshark and tshark support plugins called extcap that provide other sources of packets. It looks like tshark kicks each extcap source into action when tshark runs, and the android one opportunistically tries to make a connection to the adb port on localhost, 5037. You can see it with this command (then run termshark)

```
$ sudo nc -l -p 5037
000ehost:devices-l
```

I'm not sure what the right course of action is - but you can remove androiddump from the extcap folder if you're not otherwise using it, and that will solve the problem:

https://ask.wireshark.org/question/6810/how-to-disable-automatic-loading-of-extcap-plugins/

**Comment by kevinhwang91** [comment]
Yes, What you assume is right. After remove `/usr/lib/wireshark/extcap/androiddump` In my ArchLinux, the package captured by port 5037 is gone.
Is there another workaround to solve this issue? `wireshark` is installed by `pacman`, it will restore the `androiddump` when `wireshark` become updateable.

**Comment by gcla** [comment]
Hi @kevinhwang91 - how about this:

- replace androidddump with something like this - make sure to set it executable, `chmod +x`:

```bash
#!/usr/bin/env bash
exit 0
```

- in `pacman.conf`, add a line like this:

```
NoUpgrade = path/to/arch/linux/version/of/androiddump
```

**Comment by kevinhwang91** [comment]
pacman doesn't have `NoUpgrade`, it needs pacman.hook.

`cat /etc/pacman.d/hooks/wireshark-cli.hook`

```
[Trigger]
Operation = Install
Operation = Upgrade
Type = Package
Target = wireshark-cli

[Action]
When = PostTransaction
Exec = /usr/bin/rm /usr/lib/wireshark/extcap/androiddump
```
I know this is not an issue for termshark, but you'd better list it in the wiki.

BTW, feel free to close this issue.

**Comment by gcla** [comment]
ok, thanks.
