### ISSUE TITLE
Option to disable the Shark Fin animation 

### ISSUE THREAD

**Issue by grafael** [gcla/termshark#99]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when that shark fin animation appears. 

### Describe the solution you'd like
I would like to have an option to disable that (or even let that disabled by default).

### Describe alternatives you've considered
NA

### Additional context
NA

**Comment by pocc** [comment]
Add these to your [termshark config](https://github.com/gcla/termshark/blob/master/docs/UserGuide.md#config-file):

```
[main]
  disable-shark-fin = true
```

There are all sorts of other options you can configure in that file as well!

**Comment by grafael** [comment]
That works.
